name: Build a Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Triggers on tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      path: ${{ steps.artifact-upload.outputs.artifact-id }}
      run_id: ${{ github.run_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=21.7"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build Artifact
        id: artifact-upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          if-no-files-found: error
          retention-days: 7


  release:
    name: Release
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.ref_name }}

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
          run-id: ${{ needs.build.result.run_id }}

      - name: Verify that build artifact is present (error if not)
        run: |
          if [ ! -d "build" ]; then
              echo "Build artifact not found"
              exit 1
          fi
          echo "Build artifact found"

      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for version ${{ github.ref_name }}" \
            --draft \
            build/**