name: Deployment
on:
  workflow_run:
    workflows:
      - "Release"
    types:
      - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
        environment: production
        runs-on: ubuntu-latest

        steps:
        - name: Download Release
          run: |
            echo "Downloading release ${{ github.event.workflow_run.head_branch }}"
            gh release download ${{ github.event.workflow_run.head_branch }} --dir=build
        - name: Listing
          run: ls -la build

