name: "Deployment: ${{ github.event.workflow_run.conclusion }}"
on:
  workflow_run:
    workflows:
      - "Release"
    types:
      - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
        environment: production
        runs-on: ubuntu-latest
        permissions:
          contents: write
          packages: read

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download Release
          run: |
            echo "Downloading release ${{ github.event.workflow_run.head_branch }}"
            gh release download ${{ github.event.workflow_run.head_branch }} --dir=build
        - name: Listing
          run: ls -la build


        - name: Publish Release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}
          run: gh release edit "${{ github.event.workflow_run.head_branch }}" --draft=false

